name: textmagic

services:
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    command: tail -f /dev/null
    depends_on:
      - db
    networks:
      textmagic:

  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: main
    ports:
      - "5432:5432"

    volumes:
      - ../.local/postgres/:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      textmagic:

networks:
  textmagic:
